name: Destroy Azure Resource Group (safe)

env:
  AZURE_RESOURCE_GROUP_NAME: ${{ vars.AZURE_RESOURCE_GROUP_NAME || 'simple-react-router-rg' }}
  AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID || '' }}

on:
  workflow_dispatch:
    inputs:
      resource-group:
        description: 'Name of the Azure resource group to delete (optional; falls back to repository Variable AZURE_RESOURCE_GROUP_NAME)'
        required: false
      subscription-id:
        description: 'Azure subscription ID (optional; falls back to repository Variable AZURE_SUBSCRIPTION_ID)'
        required: false
      confirm:
        description: 'Type the resource group name again to confirm destruction (safety check)'
        required: true
      wait:
        description: 'Whether to wait for the deletion to complete (true/false)'
        required: false
        default: 'true'

permissions:
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: Destroy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          subscription-id: ${{ github.event.inputs.subscription-id || env.AZURE_SUBSCRIPTION_ID }}

      - name: Dry-run show resource group and resources (human-friendly)
        id: dry-run
        uses: azure/cli@v2
        with:
          inlineScript: |
            set -euo pipefail

            RG="${{ github.event.inputs.resource-group || env.AZURE_RESOURCE_GROUP_NAME }}"

            if [ -z "$RG" ]; then
              echo "No resource group specified. Set input 'resource-group' or repository Variable AZURE_RESOURCE_GROUP_NAME."
              exit 1
            fi

            echo "Resource group summary for: $RG"
            az group show --name "$RG" -o table || echo "Resource group '$RG' not found or access denied."

            echo
            echo "Resources in '$RG' (summary):"
            az resource list --resource-group "$RG" --query '[].{name:name,type:type,location:location}' -o table || echo "No resources or unable to list resources."

            COUNT=$(az resource list --resource-group "$RG" --query 'length(@)' -o tsv || echo 0)
            echo
            echo "Resource count: $COUNT"

      - name: Preview create JSON file of resources to be deleted
        id: preview-json
        uses: azure/cli@v2
        with:
          inlineScript: |
            set -euo pipefail

            RG="${{ github.event.inputs.resource-group || env.AZURE_RESOURCE_GROUP_NAME }}"
            name: Destroy Azure Resource Group (safe)

            env:
              AZURE_RESOURCE_GROUP_NAME: ${{ vars.AZURE_RESOURCE_GROUP_NAME || 'simple-react-router-rg' }}
              AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID || '' }}

            on:
              workflow_dispatch:
                inputs:
                  resource-group:
                    description: 'Name of the Azure resource group to delete (optional; falls back to repository Variable AZURE_RESOURCE_GROUP_NAME)'
                    required: false
                  subscription-id:
                    description: 'Azure subscription ID (optional; falls back to repository Variable AZURE_SUBSCRIPTION_ID)'
                    required: false
                  confirm:
                    description: 'Type the resource group name again to confirm destruction (safety check)'
                    required: true
                  wait:
                    description: 'Whether to wait for the deletion to complete (true/false)'
                    required: false
                    default: 'true'

            permissions:
              contents: read

            jobs:
              destroy:
                runs-on: ubuntu-latest
                environment: Destroy
                steps:
                  - name: Checkout
                    uses: actions/checkout@v4

                  - name: Azure Login
                    uses: azure/login@v2
                    with:
                      creds: ${{ secrets.AZURE_CREDENTIALS }}
                      subscription-id: ${{ github.event.inputs.subscription-id || env.AZURE_SUBSCRIPTION_ID }}

                  - name: Dry-run: show resource group and resources (human-friendly)
                    id: dry-run
                    uses: azure/cli@v2
                    with:
                      inlineScript: |
                        set -euo pipefail

                        RG="${{ github.event.inputs.resource-group || env.AZURE_RESOURCE_GROUP_NAME }}"

                        if [ -z "$RG" ]; then
                          echo "No resource group specified. Set input 'resource-group' or repository Variable AZURE_RESOURCE_GROUP_NAME."
                          exit 1
                        fi

                        echo "Resource group summary for: $RG"
                        az group show --name "$RG" -o table || echo "Resource group '$RG' not found or access denied."

                        echo
                        echo "Resources in '$RG' (summary):"
                        az resource list --resource-group "$RG" --query '[].{name:name,type:type,location:location}' -o table || echo "No resources or unable to list resources."

                        COUNT=$(az resource list --resource-group "$RG" --query 'length(@)' -o tsv || echo 0)
                        echo
                        echo "Resource count: $COUNT"

                  - name: Preview: create JSON file of resources to be deleted
                    id: preview-json
                    uses: azure/cli@v2
                    with:
                      inlineScript: |
                        set -euo pipefail

                        RG="${{ github.event.inputs.resource-group || env.AZURE_RESOURCE_GROUP_NAME }}"
                        name: Destroy Azure Resource Group (safe)

                        env:
                          AZURE_RESOURCE_GROUP_NAME: ${{ vars.AZURE_RESOURCE_GROUP_NAME || 'simple-react-router-rg' }}
                          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID || '' }}

                        on:
                          workflow_dispatch:
                            inputs:
                              resource-group:
                                description: 'Name of the Azure resource group to delete (optional; falls back to repository Variable AZURE_RESOURCE_GROUP_NAME)'
                                required: false
                              subscription-id:
                                description: 'Azure subscription ID (optional; falls back to repository Variable AZURE_SUBSCRIPTION_ID)'
                                required: false
                              confirm:
                                description: 'Type the resource group name again to confirm destruction (safety check)'
                                required: true
                              wait:
                                description: 'Whether to wait for the deletion to complete (true/false)'
                                required: false
                                default: 'true'

                        permissions:
                          contents: read

                        jobs:
                          destroy:
                            runs-on: ubuntu-latest
                            environment: Destroy
                            steps:
                              - name: Checkout
                                uses: actions/checkout@v4

                              - name: Azure Login
                                uses: azure/login@v2
                                with:
                                  creds: ${{ secrets.AZURE_CREDENTIALS }}
                                  subscription-id: ${{ github.event.inputs.subscription-id || env.AZURE_SUBSCRIPTION_ID }}

                              - name: Dry-run: show resource group and resources (human-friendly)
                                id: dry-run
                                uses: azure/cli@v2
                                with:
                                  inlineScript: |
                                    set -euo pipefail

                                    RG="${{ github.event.inputs.resource-group || env.AZURE_RESOURCE_GROUP_NAME }}"

                                    if [ -z "$RG" ]; then
                                      echo "No resource group specified. Set input 'resource-group' or repository Variable AZURE_RESOURCE_GROUP_NAME."
                                      exit 1
                                    fi

                                    echo "Resource group summary for: $RG"
                                    az group show --name "$RG" -o table || echo "Resource group '$RG' not found or access denied."

                                    echo
                                    echo "Resources in '$RG' (summary):"
                                    az resource list --resource-group "$RG" --query '[].{name:name,type:type,location:location}' -o table || echo "No resources or unable to list resources."

                                    COUNT=$(az resource list --resource-group "$RG" --query 'length(@)' -o tsv || echo 0)
                                    echo
                                    echo "Resource count: $COUNT"

                              - name: Preview: create JSON file of resources to be deleted
                                id: preview-json
                                uses: azure/cli@v2
                                with:
                                  inlineScript: |
                                    set -euo pipefail

                                    RG="${{ github.event.inputs.resource-group || env.AZURE_RESOURCE_GROUP_NAME }}"
                                    echo "Creating resources-to-delete.json for: $RG"
                                    az resource list --resource-group "$RG" -o json > resources-to-delete.json || echo '[]' > resources-to-delete.json

                              - name: Upload preview artifact (resources-to-delete.json)
                                uses: actions/upload-artifact@v4
                                with:
                                  name: resource-preview
                                  path: resources-to-delete.json

                              - name: Confirm input matches resource group name
                                id: confirm-check
                                run: |
                                  set -euo pipefail

                                  RG="${{ github.event.inputs.resource-group || env.AZURE_RESOURCE_GROUP_NAME }}"
                                  CONFIRM="${{ github.event.inputs.confirm }}"

                                  if [ "$RG" != "$CONFIRM" ]; then
                                    echo "Confirmation did not match the resource group name. Aborting to avoid accidental deletion."
                                    echo "Re-run the workflow and enter the resource group name exactly in the 'confirm' field to proceed."
                                    exit 1
                                  fi
                                  echo "Confirmed: $RG"

                              - name: Delete resource group
                                if: always()
                                uses: azure/cli@v2
                                with:
                                  inlineScript: |
                                    set -euo pipefail

                                    RG="${{ github.event.inputs.resource-group || env.AZURE_RESOURCE_GROUP_NAME }}"
                                    WAIT="${{ github.event.inputs.wait }}"

                                    echo "Deleting resource group: $RG"

                                    if [ "$WAIT" = "true" ]; then
                                      az group delete --name "$RG" --yes
                                      echo "Deletion completed."
                                    else
                                      az group delete --name "$RG" --yes --no-wait
                                      echo "Deletion submitted (no-wait)."
                                    fi

                              - name: Show remaining resource groups (informational)
                                if: always()
                                uses: azure/cli@v2
                                with:
                                  inlineScript: |
                                    echo "Listing resource groups in the current subscription (top 50):"
                                    az group list --query '[].{name:name,location:location}' -o table | head -n 50 || true
