name: Destroy Azure Resource Group (safe)

env:
    AZURE_RESOURCE_GROUP_NAME: ${{ vars.AZURE_RESOURCE_GROUP_NAME || 'simple-react-router-rg' }}
    AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID || '' }}

on:
    workflow_dispatch:
        inputs:
            resource-group:
                description: "Name of the Azure resource group to delete (optional; falls back to repository Variable AZURE_RESOURCE_GROUP_NAME)"
                required: false
            subscription-id:
                description: "Azure subscription ID (optional; falls back to repository Variable AZURE_SUBSCRIPTION_ID)"
                required: false
            confirm:
                description: "Type the resource group name again to confirm destruction (safety check)"
                required: true
            wait:
                description: "Whether to wait for the deletion to complete (true/false)"
                required: false
                default: "true"

permissions:
    contents: read

jobs:
    destroy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Azure Login
              uses: azure/login@v2
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Set Azure subscription (if provided)
              if: ${{ github.event.inputs['subscription-id'] != '' || env.AZURE_SUBSCRIPTION_ID != '' }}
              run: |
                  set -euo pipefail
                  SUB="${{ github.event.inputs.subscription-id || env.AZURE_SUBSCRIPTION_ID }}"
                  if [ -n "$SUB" ]; then
                    echo "Setting subscription to $SUB"
                    az account set --subscription "$SUB"
                  else
                    echo "No subscription-id provided; using subscription from login credentials."
                  fi

            - name: Verify Azure account
              run: |
                  set -euo pipefail
                  echo "Azure account info:"
                  az account show -o table || echo "Unable to show account; login may have failed."

            - name: Dry-run show resource group and resources (human-friendly)
              id: dry-run
              uses: azure/cli@v2
              with:
                  inlineScript: |
                      set -euo pipefail

                      RG="${{ github.event.inputs.resource-group || env.AZURE_RESOURCE_GROUP_NAME }}"

                      if [ -z "$RG" ]; then
                        echo "No resource group specified. Set input 'resource-group' or repository Variable AZURE_RESOURCE_GROUP_NAME."
                        exit 1
                      fi

                      echo "Resource group summary for: $RG"
                      az group show --name "$RG" -o table || echo "Resource group '$RG' not found or access denied."

                      echo
                      echo "Resources in '$RG' (summary):"
                      az resource list --resource-group "$RG" --query '[].{name:name,type:type,location:location}' -o table || echo "No resources or unable to list resources."

                      COUNT=$(az resource list --resource-group "$RG" --query 'length(@)' -o tsv || echo 0)
                      echo
                      echo "Resource count: $COUNT"

            - name: Confirm destruction
              run: |
                  set -euo pipefail

                  RG="${{ github.event.inputs.resource-group || env.AZURE_RESOURCE_GROUP_NAME }}"
                  CONFIRM="${{ github.event.inputs.confirm || '' }}"

                  if [ -z "$RG" ]; then
                    echo "No resource group resolved; cannot confirm."
                    exit 1
                  fi

                  if [ -z "$CONFIRM" ]; then
                    echo "Confirmation input 'confirm' is empty. Please type the resource group name to confirm destruction."
                    exit 1
                  fi

                  if [ "$CONFIRM" != "$RG" ]; then
                    echo "Confirmation mismatch. Expected: '$RG'  Received: '$CONFIRM'"
                    echo "Aborting to avoid accidental deletion."
                    exit 1
                  fi

                  echo "Confirmation matches resource group name. Safe to proceed."

            - name: Delete resource group
              id: delete-rg
              uses: azure/cli@v2
              with:
                  inlineScript: |
                      set -euo pipefail

                      RG="${{ github.event.inputs.resource-group || env.AZURE_RESOURCE_GROUP_NAME }}"
                      WAIT="${{ github.event.inputs.wait || 'true' }}"
                      # Polling config
                      POLL_INTERVAL_SECONDS=10
                      POLL_TIMEOUT_SECONDS=900  # 15 minutes

                      if [ -z "$RG" ]; then
                        echo "No resource group resolved; cannot delete."
                        exit 1
                      fi

                      echo "Proceeding to delete resource group: $RG (wait=$WAIT)"

                      if [ "${WAIT,,}" = "false" ] || [ "${WAIT,,}" = "no" ] || [ "${WAIT,,}" = "0" ]; then
                        echo "Starting deletion (no-wait)."
                        az group delete --name "$RG" --yes --no-wait || true
                        echo "Delete requested. The operation is running asynchronously."
                      else
                        echo "Starting deletion and waiting for completion (az group delete blocks until finished)."
                        # az group delete without --no-wait will wait; still check existence afterwards
                        az group delete --name "$RG" --yes
                        echo "az group delete returned. Verifying the resource group was removed..."
                      fi

                      # Poll until the group no longer exists or timeout
                      START_TS=$(date +%s)
                      while true; do
                        EXISTS=$(az group exists --name "$RG" -o tsv || echo false)
                        if [ "$EXISTS" = "false" ]; then
                          echo "Resource group '$RG' no longer exists. Deletion confirmed."
                          break
                        fi

                        NOW=$(date +%s)
                        ELAPSED=$((NOW - START_TS))
                        if [ $ELAPSED -ge $POLL_TIMEOUT_SECONDS ]; then
                          echo "Timed out waiting for resource group deletion after ${POLL_TIMEOUT_SECONDS}s."
                          echo "Last known state: exists=$EXISTS"
                          exit 2
                        fi

                        echo "Resource group '$RG' still exists (elapsed ${ELAPSED}s). Waiting ${POLL_INTERVAL_SECONDS}s before rechecking..."
                        sleep $POLL_INTERVAL_SECONDS
                      done

                      echo "Deletion step completed."
